name: flutter_clean_arch
description: Flutter quick start project with clean architecture concepts.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # View
  auto_route: ^0.5.0
  division: ^0.8.8
  flushbar: ^1.10.4
  # BLoC & Data
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  flutter_bloc: ^6.0.1
  chopper: ^3.0.2
  flutter_secure_storage: ^3.3.3
  # DI
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  # Functional & Reactive
  dartz: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.0.0
  effective_dart: ^1.2.0
  pedantic: ^1.8.0
  build_runner: ^1.10.0
  # View
  auto_route_generator: ^0.5.0
  # BLoC & Data
  freezed: ^0.10.9
  json_serializable: ^3.3.0
  bloc_test: ^7.0.0
  chopper_generator: ^3.0.2
  # DI
  injectable_generator: ^0.4.0+1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # Adding assets: https://flutter.dev/assets-and-images/#from-packages
  # Resolution specific assets: https://flutter.dev/assets-and-images/#resolution-aware.
  # Adding fonts: https://flutter.dev/custom-fonts/#from-packages

# privent accidental publishing to pub.dev using `pub publish`
publish_to: "none"
